Feature/user authentication
oleksandra-shershen/library-service-project pull request #6
Opened 2024-06-13 19:40 UTC by Boyok1337

implement MVC for user
register admin for user model
added JWT auth
update requirements

2024-06-13 19:49 UTC, Gilgumish approved these changes
well done!

2024-06-13 20:46 UTC, VitalyBashkiser approved these changes
It looks awesome 👍

2024-06-13 20:46 UTC, VitalyBashkiser commented on library_service/settings.py
> +    # User apps
Good idea with the # separation of libraries and apps 👍

2024-06-13 20:46 UTC, VitalyBashkiser commented on user/models.py
> +    objects = UserManager()
GJ 👍

2024-06-13 20:46 UTC, VitalyBashkiser commented on user/serializers.py
> +        return user
Well done 👍

2024-06-13 22:12 UTC, oleksandra-shershen requested changes

2024-06-13 22:12 UTC, oleksandra-shershen commented on requirements.txt
> +inflection==0.5.1
Do we really need all these packages now?

2024-06-13 22:12 UTC, oleksandra-shershen commented on user/models.py
> +    email = models.EmailField(_("email address"), unique=True)
(Optional) You can write validators for fields. For example:
```
email = models.EmailField(
        _("email address"),
        unique=True,
        validators=[RegexValidator(
            regex='^[\w\.-]+@[\w\.-]+\.\w+$',
            message=_("Enter a valid email address"),
            code='invalid_email'
        )]
    )
```

2024-06-13 22:12 UTC, oleksandra-shershen commented on user/models.py
> +    def _create_user(self, email, password, **extra_fields):
(Optional) Added docstrings to classes and methods to describe their purpose

2024-06-14 06:05 UTC, oleksandra-shershen approved these changes

2024-06-14 06:25 UTC, merged